### PR TITLE
Cleanup async stuff and class declarations

### PR DESCRIPTION
**Pull request by devoxin**
Mostly a minor cleanup, rather than use await only to return another promise we can just return the promise directly with modifications on top via `.then`.

Class declarations don't need to be declared using `let`.

### CODE REVIEW

**Comment by komfluent** [comment]
The only syntactical difference I see is in the bans api. I would like to keep the syntax the same over all the api's to mitigate confusion. That's the main reason I hesitate to accept this pull request.

**Comment by devoxin** [comment]
Will go through and cleanup the syntax in the other files later

**Review by komfluent — CHANGES_REQUESTED** [review]
Once you fix up the syntax in the other files I will go through and check everything, if everything checks out then It will likely be accepted.

**Comment by ember-ana** [comment]
I'd say this is a welcome change from what I've seen so far. `.then` syntax for centra is definitely cleaner.

**Comment by komfluent** [comment]
> I'd say this is a welcome change from what I've seen so far. `.then` syntax for centra is definitely cleaner.

I agree. I do think the code will be cleaner. I just want to make sure if there is a breaking change it is consistent across all the api's.

**Comment by komfluent** [comment]
Actually. I wasn't understanding. This will still return a promise, that means it isn't a breaking change. Ok I feel a lot better about this 😂

**Comment by ember-ana** [comment]
just syntax cleanup :)

**Comment by komfluent** [comment]
Alright cool! 👍

**Comment by devoxin** [comment]
This should be ready for merging if everything is up to standard.

**Comment by ember-ana** [comment]
This should be ded now as we have v2. Feel free to PR any changes there.

**Pull request closed without merging**
